global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "log-ingestor"
    static_configs:
      - targets: ["log-ingestor:8000"]

  - job_name: "anomaly-detector"
    static_configs:
      - targets: ["anomaly-detector:8001"]

  - job_name: "alert-service"
    static_configs:
      - targets: ["alert-service:8002"]
